### ISSUE TITLE
Showing Showcase

### ISSUE THREAD

**Issue by 3xploiton3** [ebullient/obsidian-show-whitespace-cm6#167]
Can you add some showcase before and after

GIF would be okay

**Comment by ebullient** [comment]
Show all whitespace, outline list markers:
<img width="374" alt="image" src="https://github.com/user-attachments/assets/2e102973-e432-4885-a904-362d12604e98">

Show consecutive whitespace, outline list markers: 
<img width="384" alt="image" src="https://github.com/user-attachments/assets/e91cb05d-387d-453d-bcb7-f08075a6ccb2">

Outline list markers:
<img width="338" alt="image" src="https://github.com/user-attachments/assets/b25dc1b3-5238-4fd4-b41a-f69935864098">

**Comment by 3xploiton3** [comment]
add to readme would be better for entry user

**Comment by ebullient** [comment]
done
