### ISSUE TITLE
"No appropriate version found" when attempting to install on Obsidian v1.4.16

### ISSUE THREAD

**Issue by nheape** [ebullient/obsidian-show-whitespace-cm6#24]
Getting the popup when I attempt to install v0.1.5 from the Community Plugins within Obsidian (Windows 10).

**Comment by ebullient** [comment]
I'm running the plugin with Version 1.5.2 (Installer 1.4.16).
minimum Obsidian app version is "1.5.0"

Can you clarify what version of Obsidian you have?

**Comment by nheape** [comment]
I'm running v1.4.16, which is the latest public version of Obsidian. Do I need to have early access to make this plugin work?

**Comment by ebullient** [comment]
https://obsidian.md/changelog/2023-11-20-desktop-v1.5.0/

I'm not sure when this version will move out of catalyst. If you want to try it, download the zip from here (https://github.com/ebullient/obsidian-show-whitespace-cm6/releases/tag/0.1.5), extract it into your .obsidian/plugins directory (rename to `show-whitespace-cm6`). Edit manifest.json, and change `"minAppVersion": "1.5.0"` -> `"minAppVersion": "1.4.16"`

**Comment by nheape** [comment]
Thanks for the help!
