### ISSUE TITLE
Missing spaces

### ISSUE THREAD

**Issue by notDavid** [ebullient/obsidian-show-whitespace-cm6#98]
Hi there,

Please check out whether this is a bug or me misunderstanding... line 14 and 16 show only 1 whitespace instead of 2;

Love the plugin, thank you!

```
This is a test
 line started with space
 `line started with space in code block`

- dash and space
  line started with 2 spaces
  
  line started with 2 spaces
```

![sws](https://github.com/ebullient/obsidian-show-whitespace-cm6/assets/1530401/0a3472b8-b917-45aa-b50c-065ce231fcab)

**Comment by ebullient** [comment]
So. The way spaces work here is real weird. There is only so much precision in some cases. If, e.g., you tried to use 3 spaces for indent, things get real weird.

So 2 spaces is technically enough for a continuation w/ the bullet, and that might make data available on the line a little different.

If you look in the dev console and inspect those elements, I think you'll see what I mean.
